name: HDX CLI Toolkit CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    environment: 
        name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install
      - name: Analysing the code with pylint
        run: |
          make lint
      - name: Running unit tests
        env:
            HDX_KEY: ${{ secrets.HDX_KEY_STAGE }}
            HDX_SITE: ${{ vars.HDX_SITE }}
            USER_AGENT: ${{ vars.USER_AGENT }}
            PREPREFIX: ${{ vars.PREPREFIX }}
        run: |
          hdx-toolkit configuration
          make unit_tests